name = "en-learning-dictionary"
main = "src/index.js"
compatibility_date = "2026-06-19"

workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "en_learning"
database_id = "a8c5e3e8-c527-499f-8de1-a0dd45d5e9cb"

[vars]
CACHE_TTL_SECONDS = "1209600"
BATCH_LIMIT = "50"
GOOGLE_TRANSLATE_MONTHLY_LIMIT = "450000"
GOOGLE_TRANSLATE_EXAMPLE_LIMIT = "3"
